export type {
  BaseEntity,
  EntityWithUuid,
  AuditableEntity,
  ApiResponse,
  SuccessApiResponse,
  ErrorApiResponse,
  ApiResult,
  ServerResponse,
  ServerSuccessResponse,
  ServerErrorResponse,
  ServerResult,
  AsyncOperation,
  LoadingState,
  ErrorState,
  PaginationMeta,
  PaginatedResponse,
  FormState,
  InputEvent,
  TextAreaEvent,
  FormEvent,
  ClickEvent,
  ThemeMode,
  ToastType,
  ToastMessage,
  BaseComponentProps,
  LoadableComponentProps,
  DisableableComponentProps,
  ButtonVariant,
  InputType,
  StatusType,
  SortDirection,
  KeyValuePair,
  DateRange,
  BaseFilter,
  EmitFunction,
  TypedError,
  StoreMethodResult,
  AsyncStoreResult,
  BaseStoreState,
  ApiCallConfig,
  ValidationResult,
  FileUploadConfig,
  UploadResult,
} from './common'

export type {
  PersonStats,
  PersonFollower,
  PersonFollowing,
  User,
  PostStats,
  PostLike,
  PostStory,
  Post,
  AuthState,
  AuthResponse,
  LoginRequest,
  RegisterRequest,
  Profile,
  SearchPeopleRequest,
  SearchPeopleResponse,
  FollowRequest,
  FollowResponse,
  CreatePostRequest,
  CreatePostResponse,
  PostLikeRequest,
  PostLikeResponse,
  PostStoryRequest,
  PostStoryResponse,
  FeedRequest,
  FeedResponse,
  GetProfileRequest,
  GetProfileResponse,
  LoginApiResponse,
  RegisterApiResponse,
  ProfileApiResponse,
  PostCreateApiResponse,
  PostLikeApiResponse,
  FollowApiResponse,
  SearchApiResponse,
  PostOperationResult,
  UserOperationResult,
  FollowOperationResult,
  SearchOperationResult,
  AuthStorePayload,
  RegisterStorePayload,
  PostStorePayload,
  LikePostPayload,
  FollowUserPayload,
  FetchProfilePayload,
  UserCardProps,
  PostCardProps,
  ProfileHeaderProps,
  ProfileStatsProps,
  ProfilePictureProps,
  PostInputProps,
  PostCardEmits,
  ProfileBodyEmits,
  PostInputEmits,
  PostWithoutRelations,
  UserWithoutRelations,
  UserSummary,
  PostSummary,
} from './auth'

// Component types
export type {
  ButtonProps,
  ButtonEmits,
  TextInputProps,
  TextInputEmits,
  TextAreaProps,
  TextAreaEmits,
  FormProps,
  FormEmits,
  ModalProps,
  ModalEmits,
  DropdownOption,
  DropdownProps,
  PostItemProps,
  PostItemEmits,
  ProfileCardProps,
  ProfileCardEmits,
  UserListProps,
  UserListEmits,
  SearchInputProps,
  SearchInputEmits,
} from './components'

// Constants types
export type {
  RouteKey,
  RouteValue,
  MessageKey,
  MessageValue,
  LocalStorageKey,
  LocalStorageValue,
  ApiEndpoints,
  ApiConfig,
  Environment,
  RuntimeConfig,
  HttpMethod,
  ContentType,
  ResponseStatus,
  AnimationDuration,
  Breakpoint,
  ZIndex,
} from './constants'

// Error types
export type {
  BaseError,
  ApiError,
  ValidationError,
  NetworkError,
  AuthError,
  AppError,
  ErrorHandler,
  Result,
  SafePromise,
  ErrorBoundaryState,
} from './errors'

export { HttpStatusCode } from './errors'

// Utility types
export type {
  PartialType,
  RequiredType,
  PickType,
  OmitType,
  RecordType,
  NonNullableType,
  ReturnTypeHelper,
  ParametersHelper,
  ValueOf,
  ArrayElement,
  DeepReadonly,
  DeepPartial,
  Flatten,
  OptionalFields,
  RequiredFields,
  Exact,
  Brand,
  UserId,
  PostId,
  UUID,
  Token,
  ApiSuccessResponse as UtilApiSuccessResponse,
  ApiErrorResponse as UtilApiErrorResponse,
  ApiResponseUnion,
  StoreGetter,
  StoreAction,
  AsyncStoreAction,
  ComponentProps,
  ComponentEmits,
  Ref,
  ComputedRef,
  WritableComputedRef,
  EventHandler,
  AsyncEventHandler,
  ValidationRule,
  ValidationRules,
  IfEquals,
  Mutable,
  ObjectKeys,
  ObjectValues,
  ObjectEntries,
} from './utils'

// Re-export constants
export {
  ROUTES,
  MESSAGES,
  LOCAL_STORAGE_KEYS,
  HTTP_METHODS,
  CONTENT_TYPES,
  RESPONSE_STATUS,
  VALIDATION_RULES,
  ANIMATION_DURATION,
  BREAKPOINTS,
  Z_INDEX,
} from './constants'

// Re-export error utilities
export {
  createApiError,
  createValidationError,
  createNetworkError,
  createAuthError,
  isApiError,
  isValidationError,
  isNetworkError,
  isAuthError,
} from './errors'
